export const events = [
    {
      "title": "ETHDenver",
      "startDate": "2025-02-23",
      "endDate": "2025-03-02",
      "href": "https://www.ethdenver.com/",
      "location": "Denver",
      "country": "United States",
      "continent": "North America",
      "description": "ETHDenver 2025  #BUIDLathon + Community Innovation Festival",
      "imageUrl": "https://cdn.prod.website-files.com/6509ee7744afed1c907f8f97/66916c73fade30407dbf07b4_ETHDEN2025_SEOImage_website.jpg",
      "tags": ["Hackathon", "Conference", "Festival"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "ETH Bucharest",
      "startDate": "2025-04-02",
      "endDate": "2025-04-05",
      "href": "https://www.ethbucharest.xyz/",
      "location": "Bucharest",
      "country": "Romania",
      "continent": "Europe",
      "description": "Join ETH Bucharest in 25 - 27 March 2025 for a pivotal blockchain event in Eastern Europe. Engage in workshops, networking, and a hackathon to drive Ethereum innovation and adoption.",
      "imageUrl": "",
      "tags": ["Hackathon", "Workshop", "Networking"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "ETH Seoul",
      "startDate": "2025-04-06",
      "endDate": "2025-04-13",
      "href": "https://ethseoul.org",
      "location": "Seoul",
      "country": "South Korea",
      "continent": "Asia",
      "description": "A vibrant Ethereum event in the heart of Seoul",
      "imageUrl": "",
      "tags": ["Conference", "Hackathon", "Web3"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "ETHDublin 2025",
      "startDate": "2025-05-23",
      "endDate": "2025-05-25",
      "href": "https://lu.ma/hkl5jcre",
      "location": "Dublin",
      "country": "Ireland",
      "continent": "Europe",
      "description": "",
      "imageUrl": "https://social-images.lu.ma/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=800,height=419/api/event-one?calendar_avatar=https%3A%2F%2Fimages.lumacdn.com%2Fcalendars%2Fkx%2F61284be8-5aa6-4d0a-b57d-4df3ef8c59ea&calendar_name=ETH%20Ireland&color0=%23ffffff&color1=%230b693b&color2=%237bad94&color3=%23ee9e61&host_avatar=https%3A%2F%2Fimages.lumacdn.com%2Favatars%2Fsl%2Fdec7e3f9-9b6c-4b7c-a455-a96fc844eeb4&host_name=Caol%C3%A1n%20Walsh&img=https%3A%2F%2Fimages.lumacdn.com%2Fevent-covers%2F7x%2F6df8a419-4fa2-4ee7-81cb-76295cb6fa0c&name=ETHDublin%202025",
      "tags": ["Conference", "Networking"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHKyiv",
      "startDate": "2025-06-13",
      "endDate": "2025-06-15",
      "href": "https://ethkyiv.com",
      "location": "Kyiv",
      "country": "Ukraine",
      "continent": "Europe",
      "description": "Welcome to the 1st edition of ETHKyiv, hosted this June 21-23 and bringing together participants from diverse backgrounds, including developers, designers, entrepreneurs, and blockchain enthusiasts!",
      "imageUrl": "https://ethkyiv.com/_next/image?url=%2Fimages%2Fmain-banner_01.png&w=1920&q=75",
      "tags": ["Conference", "Networking", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "DappCon",
      "startDate": "2025-06-16",
      "endDate": "2025-06-18",
      "href": "https://dappcon.io",
      "location": "Berlin",
      "country": "Germany",
      "continent": "Europe",
      "description": "The leading summit for applications & infrastructure for an open internet",
      "imageUrl": "https://framerusercontent.com/assets/EwcloiP4dkmBNB8xV0UhgCy5jE.png",
      "tags": ["DApps", "Infrastructure", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "EthCC",
      "startDate": "2025-06-30",
      "endDate": "2025-07-03",
      "href": "https://ethcc.io",
      "location": "Cannes",
      "country": "France",
      "continent": "Europe",
      "description": "Ethereum Community Conference & Workshops: June 30th to July 3rd, 2025 in Cannes",
      "imageUrl": "https://ethcc.io/ethcc7.jpg",
      "tags": ["Conference", "Workshop", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHSofia",
      "startDate": "2025-09-23",
      "endDate": "2025-09-25",
      "href": "https://ethsofia.com",
      "location": "Sofia",
      "country": "Bulgaria",
      "continent": "Europe",
      "description": "The first major Ethereum community conference in Bulgaria. Bringing ETH enthusiasts, professionals, and developers to the IT heart of the Balkans. 23 - 25 September 2025.",
      "imageUrl": "https://framerusercontent.com/assets/OHGIdIaZVjWGAwpmJhN1z6Yuh5g.png",
      "tags": ["Conference", "Community", "Networking"],
      "categories": ["Conference"]
    },
    {
      "title": "ProtoLayers Conference",
      "startDate": "2025-10-11",
      "endDate": "2025-10-11",
      "href": "https://lu.ma/protolayersprague",
      "location": "Prague, CZ",
      "description": "Join us for a  technical conference dedicated to exploring the edges of modular blockchain technology. This one-day event, held on May 30, 2024 brings together…",
      "imageUrl": "https://social-images.lu.ma/cdn-cgi/image/format=auto,fit=cover,dpr=1,background=white,quality=75,width=800,height=419/api/event-one?calendar_avatar=https%3A%2F%2Fimages.lumacdn.com%2Fcalendars%2Fgb%2F04e6c14a-bef9-4690-a55e-58dbab9f8aca&amp;calendar_name=ProtoLayers%20Builder%20Conference&amp;color0=%23ffffff&amp;color1=%23010101&amp;color2=%238b8a8a&amp;color3=%23ff3503&amp;host_avatar=https%3A%2F%2Fimages.lumacdn.com%2Favatars%2Fwx%2Fd64d0bac-aec7-4589-840e-4d4111ce4988&amp;host_name=ProtoLayers&amp;img=https%3A%2F%2Fimages.lumacdn.com%2Fevent-covers%2Fr7%2Fa289e9d1-9744-4ccc-a812-e6ac947d09cf&amp;name=ProtoLayers%20Conference"
    },
    {
      "title": "ETHPrague",
      "startDate": "2025-05-27",
      "endDate": "2025-05-29",
      "href": "https://ethprague.com/",
      "location": "Prague",
      "country": "Czech Republic",
      "continent": "Europe",
      "description": "ETHPrague - A premier Ethereum event in the heart of Europe",
      "imageUrl": "https://ethprague.com/ETHPrague_soc_share-2025.png",
      "tags": ["Conference", "Hackathon", "Community"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "ETH Belgrade",
      "startDate": "2025-06-03",
      "endDate": "2025-06-08",
      "href": "https://ethbelgrade.rs/",
      "location": "Belgrade",
      "country": "Serbia",
      "continent": "Europe",
      "description": "The most welcoming ETH event in the heart of the Balkans. Part of Belgrade Blockchain Week.",
      "imageUrl": "https://ethbelgrade.rs/eth-belgrade-og-2025.jpg",
      "tags": ["Conference", "Blockchain", "Networking"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHCluj",
      "startDate": "2025-06-26",
      "endDate": "2025-06-28",
      "href": "https://www.ethcluj.org/",
      "location": "Cluj-Napoca",
      "country": "Romania",
      "continent": "Europe",
      "description": "ETHCluj 2025 - Ethereum for everyone conference",
      "imageUrl": "https://framerusercontent.com/images/rHUxnoTTgyhaJqvDh9ZbOPH2Dd0.jpg",
      "tags": ["Conference", "Community", "Education"],
      "categories": ["Conference"]
    },
    {
      "title": "BUIDL Europe",
      "startDate": "2025-01-09",
      "endDate": "2025-01-10",
      "href": "https://buidleurope.com",
      "location": "Lisbon",
      "country": "Portugal",
      "continent": "Europe",
      "description": "Building the future of Web3 in Europe",
      "imageUrl": "",
      "tags": ["Web3", "Development", "Innovation"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHiopia",
      "startDate": "2025-01-21",
      "endDate": "2025-02-21",
      "href": "https://eth-iopia.xyz",
      "location": "Addis Ababa",
      "country": "Ethiopia",
      "continent": "Africa",
      "description": "Bringing Ethereum innovation to East Africa",
      "imageUrl": "https://eth-iopia.xyz/logo.jpg",
      "tags": ["Conference", "Community", "Innovation"],
      "categories": ["Conference"]
    },
    {
      "title": "EthereumZuri.ch",
      "startDate": "2025-01-30",
      "endDate": "2025-01-31",
      "href": "https://ethereumzuri.ch/",
      "location": "Zurich",
      "country": "Switzerland",
      "continent": "Europe",
      "description": "Switzerland's premier Ethereum event",
      "imageUrl": "https://ethereumzuri.ch/ez-soc.jpg",
      "tags": ["Conference", "Innovation", "Finance"],
      "categories": ["Conference"]
    },
    {
      "title": "NFT Paris*",
      "startDate": "2025-02-13",
      "endDate": "2025-02-14",
      "href": "https://nftparis.xyz",
      "location": "Paris",
      "country": "France",
      "continent": "Europe",
      "description": "Leading NFT and Web3 event in Europe",
      "imageUrl": "https://cdn.prod.website-files.com/62b386503a338d13fadcadf5/62b6138a5d1d73074b8826df_cam07%20(1).jpg",
      "tags": ["NFT", "Web3", "Conference"],
      "categories": ["Conference"]
    },
    {
      "title": "RWA Paris Summit*",
      "startDate": "2025-02-13",
      "endDate": "2025-02-14",
      "href": "https://rwaparis.xyz",
      "location": "Paris",
      "country": "France",
      "continent": "Europe",
      "description": "Premier summit focused on Real World Assets in blockchain",
      "imageUrl": "https://cdn.prod.website-files.com/664217a6af4422924626be6c/666c48b47d2b5659149732ef_rwarwa.png",
      "tags": ["RWA", "DeFi", "Finance"],
      "categories": ["Conference"]
    },
    {
      "title": "Consensus HK*",
      "startDate": "2025-02-18",
      "endDate": "2025-02-20",
      "href": "https://consensus-hongkong2025.coindesk.com/",
      "location": "Hong Kong",
      "country": "Hong Kong",
      "continent": "Asia",
      "description": "CoinDesk's influential crypto event bringing together DeFi, blockchain, Web3 and metaverse",
      "imageUrl": "https://consensus-hongkong2025.coindesk.com/site/consensushongkong202/images/userfiles/metadata/hk-25/HK25-Generic.png",
      "tags": ["DeFi", "Blockchain", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "ZKDay",
      "startDate": "2025-02-20",
      "endDate": "2025-02-20",
      "href": "https://zklab.systems/zk-village",
      "location": "Denver",
      "country": "United States",
      "continent": "North America",
      "description": "A day dedicated to Zero Knowledge proofs and their applications",
      "imageUrl": "",
      "tags": ["ZK-Proofs", "Technical", "Privacy"],
      "categories": ["Conference"]
    },
    {
      "title": "Pragma Denver",
      "startDate": "2025-02-25",
      "endDate": "2025-02-25",
      "href": "https://ethglobal.com/events/pragma-denver2025",
      "location": "Denver",
      "country": "United States",
      "continent": "North America",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "Modular Carnival",
      "startDate": "2025-02-25",
      "endDate": "2025-03-01",
      "href": "https://modularcarnival.xyz",
      "location": "Belo Horizonte",
      "country": "Brazil",
      "continent": "South America",
      "description": "Celebrating modular blockchain technology and innovation",
      "imageUrl": "https://static.wixstatic.com/media/94db02_460ea9b1478f4d939a2d8d0640bfde31~mv2.png/v1/fill/w_320,h_179,al_c,q_95,enc_avif,quality_auto/94db02_460ea9b1478f4d939a2d8d0640bfde31~mv2.png",
      "tags": ["Modular", "Blockchain", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "ETH Pondy",
      "startDate": "2025-03-28",
      "endDate": "2025-03-30",
      "href": "https://ethpondy.xyz",
      "location": "Pondicherry",
      "country": "India",
      "continent": "Asia",
      "description": "Shaping the future of Blockchain in India",
      "imageUrl": "",
      "tags": ["Conference", "Community", "Innovation"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHTaipei",
      "startDate": "2025-04-01",
      "endDate": "2025-04-02",
      "href": "https://ethtaipei.org",
      "location": "Taipei",
      "country": "Taiwan",
      "continent": "Asia",
      "description": "Bringing together teams from around the world to participate in hackathon and conference focusing on Ethereum application and technology.",
      "imageUrl": "https://ethtaipei.org/images/ethtaipei-meta-image.jpg",
      "tags": ["Hackathon", "Conference", "Technology"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "Pragma Taipei",
      "startDate": "2025-04-03",
      "endDate": "2025-04-03",
      "href": "https://ethglobal.com/events/pragma-taipei",
      "location": "Taipei",
      "country": "Taiwan",
      "continent": "Asia",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHGlobal Taipei",
      "startDate": "2025-04-04",
      "endDate": "2025-04-06",
      "href": "https://ethglobal.com/events/taipei",
      "location": "Taipei",
      "country": "Taiwan",
      "continent": "Asia",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Hackathon", "Developer", "Web3"],
      "categories": ["Hackathon"]
    },
    {
      "title": "zkHack",
      "startDate": "2025-04-11",
      "endDate": "2025-04-13",
      "href": "https://zkhack.dev",
      "location": "Seoul",
      "country": "South Korea",
      "continent": "Asia",
      "description": "Zero Knowledge Proof hackathon and workshops",
      "imageUrl": "",
      "tags": ["ZK-Proofs", "Hackathon", "Technical"],
      "categories": ["Hackathon"]
    },
    {
      "title": "BUIDL Asia",
      "startDate": "2025-04-15",
      "endDate": "2025-04-16",
      "href": "https://www.buidl.asia/",
      "location": "Seoul",
      "country": "South Korea",
      "continent": "Asia",
      "description": "Asia's premier blockchain development conference",
      "imageUrl": "",
      "tags": ["Development", "Blockchain", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHDubai",
      "startDate": "2025-04-28",
      "endDate": "2025-04-29",
      "href": "https://www.ethdubaiconf.org/",
      "location": "Dubai",
      "country": "United Arab Emirates",
      "continent": "Asia",
      "description": "The Ethereum dev conference focusing on DeFi, privacy, L2s, AVS, AI Agents, intents, and Account Abstraction",
      "imageUrl": "https://www.ethdubaiconf.org/ethdubaicard1.png",
      "tags": ["DeFi", "Privacy", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "Staking Summit*",
      "startDate": "2025-04-28",
      "endDate": "2025-04-29",
      "href": "https://stakingsummit.com",
      "location": "Dubai",
      "country": "United Arab Emirates",
      "continent": "Asia",
      "description": "The premier staking event bringing together top protocols, validators and investors",
      "imageUrl": "https://framerusercontent.com/assets/jMgdXFlxexhLiYYWPd8Kgep6mhk.png",
      "tags": ["Staking", "DeFi", "Investment"],
      "categories": ["Conference"]
    },
    {
      "title": "TOKEN2049 Dubai*",
      "startDate": "2025-04-30",
      "endDate": "2025-05-01",
      "href": "https://token2049.com",
      "location": "Dubai",
      "country": "United Arab Emirates",
      "continent": "Asia",
      "description": "Global conference series where decision-makers in the crypto ecosystem connect to exchange ideas and shape the industry",
      "imageUrl": "https://static.wixstatic.com/media/df5f7a_8ec2fa25938e484a8cc2dc11ef6ed2f7~mv2.png/v1/fill/w_2500,h_1352,al_c/df5f7a_8ec2fa25938e484a8cc2dc11ef6ed2f7~mv2.png",
      "tags": ["Crypto", "Networking", "Industry"],
      "categories": ["Conference"]
    },
    {
      "title": "FarCon",
      "startDate": "2025-05-01",
      "endDate": "2025-05-04",
      "href": "https://farcon.nyc",
      "location": "New York",
      "country": "United States",
      "continent": "North America",
      "description": "NYC's coziest corner for blockchain innovation",
      "imageUrl": "https://framerusercontent.com/images/h11bkB3NvpEYvJPJWdaaBBpz4rU.png",
      "tags": ["Blockchain", "Community", "Innovation"],
      "categories": ["Conference"]
    },
    {
      "title": "ETH Lisbon",
      "startDate": "2025-05-09",
      "endDate": "2025-05-11",
      "href": "https://ethlisbon.org",
      "location": "Lisbon",
      "country": "Portugal",
      "continent": "Europe",
      "description": "ETHLisbon brings top builders and industry leaders to tackle real-world challenges around privacy, identity, and more",
      "imageUrl": "https://framerusercontent.com/assets/k3t9FtPBibQBemLXMzCGQo0.gif",
      "tags": ["Privacy", "Identity", "Technical"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "Consensus Toronto*",
      "startDate": "2025-05-14",
      "endDate": "2025-05-16",
      "href": "https://consensus2025.coindesk.com/",
      "location": "Toronto",
      "country": "Canada",
      "continent": "North America",
      "description": "CoinDesk's influential crypto event bringing together all sides of DeFi, blockchain, Web3 and the metaverse",
      "imageUrl": "https://consensus2025.coindesk.com/site/consensus2025/images/userfiles/metadata/2025/C25-Generic.png",
      "tags": ["DeFi", "Blockchain", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "Edge Esmeralda",
      "startDate": "2025-05-24",
      "endDate": "2025-06-21",
      "href": "https://edgeesmeralda.com",
      "location": "Healdsburg",
      "country": "United States",
      "continent": "North America",
      "description": "Edge Esmeralda 2025 - Innovation retreat",
      "imageUrl": "",
      "tags": ["Innovation", "Community", "Retreat"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHGlobal Prague",
      "startDate": "2025-05-30",
      "endDate": "2025-06-01",
      "href": "https://ethglobal.com/events/prague",
      "location": "Prague",
      "country": "Czech Republic",
      "continent": "Europe",
      "description": "Bringing developers onchain to build the future of the internet.",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Hackathon", "Developer", "Web3"],
      "categories": ["Hackathon"]
    },
    {
      "title": "Pragma Prague",
      "startDate": "2025-05-29",
      "endDate": "2025-05-29",
      "href": "https://ethglobal.com/events/pragma-prague",
      "location": "Prague",
      "country": "Czech Republic",
      "continent": "Europe",
      "description": "Bringing developers onchain to build the future of the internet.",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "Non Fungible Conference*",
      "startDate": "2025-06-04",
      "endDate": "2025-06-06",
      "href": "https://nonfungibleconference.com",
      "location": "Lisbon",
      "country": "Portugal",
      "continent": "Europe",
      "description": "NFC",
      "imageUrl": "",
      "tags": ["NFT", "Conference", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "Offscript",
      "startDate": "2025-06-11",
      "endDate": "2025-06-15",
      "href": "https://offscript.web3creatives.com/",
      "location": "San Miguel de Allende",
      "country": "Mexico",
      "continent": "North America",
      "description": "Offscript | The event for creatives in web3",
      "imageUrl": "",
      "tags": ["Creative", "Web3", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "ProtocolBerg",
      "startDate": "2025-06-12",
      "endDate": "2025-06-13",
      "href": "https://protocol.berlin",
      "location": "Berlin",
      "country": "Germany",
      "continent": "Europe",
      "description": "Protocol Berg is a two-day protocol and research focused technical conference",
      "imageUrl": "https://protocol.berlin/protocol-berg-twitter.png?cache-break-2",
      "tags": ["Protocol", "Research", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "NFT NYC*",
      "startDate": "2025-06-23",
      "endDate": "2025-06-25",
      "href": "https://nft.nyc",
      "location": "New York",
      "country": "United States",
      "continent": "North America",
      "description": "The Super Bowl of NFTs - Leading speakers and best projects in the NFT ecosystem",
      "imageUrl": "https://www.nft.nyc/hubfs/nftnyc2021-eventbrite-header.png",
      "tags": ["NFT", "Conference", "Networking"],
      "categories": ["Conference"]
    },
    {
      "title": "Permissionless IV",
      "startDate": "2025-06-24",
      "endDate": "2025-06-26",
      "href": "https://blockworks.co/event/permissionless-iv",
      "location": "Brooklyn",
      "country": "United States",
      "continent": "North America",
      "description": "The definitive gathering for crypto's technical pioneers, creators, and builders who drive our industry forward",
      "imageUrl": "https://permissionless-iv.vercel.app/_next/image?url=https://blockworks-co.imgix.net/wp-content/uploads/2024/11/PMLSIV_banner_20241114a-1.png&w=1920&q=75&webp=false",
      "tags": ["DeFi", "Infrastructure", "Technical"],
      "categories": ["Conference"]
    },
    {
      "title": "Pragma Cannes",
      "startDate": "2025-07-03",
      "endDate": "2025-07-03",
      "href": "https://ethglobal.com/events/pragma-cannes",
      "location": "Cannes",
      "country": "France",
      "continent": "Europe",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHGlobal Cannes",
      "startDate": "2025-07-04",
      "endDate": "2025-07-06",
      "href": "https://ethglobal.com/events/cannes",
      "location": "Cannes",
      "country": "France",
      "continent": "Europe",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Hackathon", "Developer", "Web3"],
      "categories": ["Hackathon"]
    },
    {
      "title": "Pragma New York",
      "startDate": "2025-08-14",
      "endDate": "2025-08-14",
      "href": "https://ethglobal.com/events/pragma-newyork2025",
      "location": "New York City",
      "country": "United States",
      "continent": "North America",
      "description": "Bringing developers onchain to build the future of the internet.",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "NapulETH",
      "startDate": "2025-07-16",
      "endDate": "2025-07-19",
      "href": "https://napuleth.org/",
      "location": "Naples",
      "country": "Italy",
      "continent": "Europe",
      "description": "Biggest Web3 Event In Southern Italy",
      "imageUrl": "",
      "tags": ["Web3", "Conference", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "SBC",
      "startDate": "2025-08-04",
      "endDate": "2025-08-06",
      "href": "https://www.sbc-conference.com/2025/",
      "location": "Berkeley",
      "country": "United States",
      "continent": "North America",
      "description": "The Science of Blockchain Conference 2025",
      "imageUrl": "",
      "tags": ["Academic", "Research", "Blockchain"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHGlobal New York",
      "startDate": "2025-08-15",
      "endDate": "2025-08-17",
      "href": "https://ethglobal.com/events/newyork2025",
      "location": "New York",
      "country": "United States",
      "continent": "North America",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Hackathon", "Developer", "Web3"],
      "categories": ["Hackathon"]
    },
    {
      "title": "Web3 Lagos Conference",
      "startDate": "2025-08-28",
      "endDate": "2025-08-30",
      "href": "https://event.web3bridge.com",
      "location": "Lagos",
      "country": "Nigeria",
      "continent": "Africa",
      "description": "Building a Sustainable web3 community in Africa",
      "imageUrl": "",
      "tags": ["Web3", "Community", "Development"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHWarsaw",
      "startDate": "2025-09-04",
      "endDate": "2025-09-07",
      "href": "https://ethwarsaw.dev",
      "location": "Warsaw",
      "country": "Poland",
      "continent": "Europe",
      "description": "EthWarsaw 2025 - Poland's premier Ethereum event",
      "imageUrl": "",
      "tags": ["Conference", "Hackathon", "Community"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "EthSafari",
      "startDate": "2025-09-08",
      "endDate": "2025-09-15",
      "href": "https://ethsafari.xyz/",
      "location": "Nairobi",
      "country": "Kenya",
      "continent": "Africa",
      "description": "Web3 builders conference East Africa",
      "imageUrl": "",
      "tags": ["Conference", "Web3", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "Boston Blockchain Week",
      "startDate": "2025-09-08",
      "endDate": "2025-09-11",
      "href": "https://bostonblockchainweek.com",
      "location": "Quincy",
      "country": "United States",
      "continent": "North America",
      "description": "The preeminent annual event celebrating the global blockchain and Web3 hub in Greater Boston",
      "imageUrl": "",
      "tags": ["Blockchain", "Web3", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "Pragma New Delhi",
      "startDate": "2025-09-25",
      "endDate": "2025-09-25",
      "href": "https://ethglobal.com/events/pragma-newdelhi",
      "location": "New Delhi",
      "country": "India",
      "continent": "Asia",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Developer", "Technical", "Web3"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHGlobal New Delhi",
      "startDate": "2025-09-26",
      "endDate": "2025-09-28",
      "href": "https://ethglobal.com/events/newdelhi",
      "location": "New Delhi",
      "country": "India",
      "continent": "Asia",
      "description": "Bringing developers onchain to build the future of the internet",
      "imageUrl": "https://ethglobal.com/og.png",
      "tags": ["Hackathon", "Developer", "Web3"],
      "categories": ["Hackathon"]
    },
    {
      "title": "TOKEN2049 Singapore*",
      "startDate": "2025-10-01",
      "endDate": "2025-10-02",
      "href": "https://asia.token2049.com/",
      "location": "Singapore",
      "country": "Singapore",
      "continent": "Asia",
      "description": "World's largest crypto event connecting decision-makers to shape the industry",
      "imageUrl": "https://static.wixstatic.com/media/bb716a_9c36a2603e974703814b39f7ac0ff1ce%7Emv2.png/v1/fit/w_2500,h_1330,al_c/bb716a_9c36a2603e974703814b39f7ac0ff1ce%7Emv2.png",
      "tags": ["Crypto", "Networking", "Industry"],
      "categories": ["Conference"]
    },
    {
      "title": "Encode London 2025",
      "startDate": "2025-10-24",
      "endDate": "2025-10-26",
      "href": "https://lu.ma/Encode-London-25/",
      "location": "London",
      "country": "United Kingdom",
      "continent": "Europe",
      "description": "Dual-track event focusing on innovation and hands-on building",
      "imageUrl": "https://social-images.lu.ma/cdn-cgi/image/format=auto,fit=cover,dpr=1,anim=false,background=white,quality=75,width=800,height=419/api/event-one",
      "tags": ["Innovation", "Development", "Technical"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "Zugrama India",
      "startDate": "2025-01-05",
      "endDate": "2025-02-16",
      "href": "https://zugrama.org/",
      "location": "Thiruvananthapuram",
      "country": "India",
      "continent": "Asia",
      "description": "A pop-village experiment exploring technology in a co-living setup",
      "imageUrl": "https://framerusercontent.com/images/wJDirYhhSH8znG0hz0hyH3wqOlE.png",
      "tags": ["Community", "Innovation", "Co-living"],
      "categories": ["Community"]
    },
    {
      "title": "EthOxford",
      "startDate": "2025-02-07",
      "endDate": "2025-02-09",
      "href": "https://ethoxford.io/",
      "location": "Oxford",
      "country": "United Kingdom",
      "continent": "Europe",
      "description": "Join the best builders for a 3 day hackathon hosted at Oxford University",
      "imageUrl": "https://ethoxford.io/assets/images/share.jpg?v=7e796eda",
      "tags": ["Hackathon", "University", "Developer"],
      "categories": ["Hackathon"]
    },
    {
      "title": "ETHVietnam 2025",
      "startDate": "2025-04-12",
      "endDate": "2025-04-12",
      "href": "https://eth-vietnam.com",
      "location": "Ho Chi Minh City",
      "country": "Vietnam",
      "continent": "Asia",
      "description": "Vietnam's premier Ethereum event",
      "imageUrl": "http://static1.squarespace.com/static/629856e64f44db3799f8e3f6/t/65c04e1059e3477a33a1c105/1707101732532/COVER.png?format=1500w",
      "tags": ["Conference", "Community", "Development"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHDam III",
      "startDate": "2025-05-09",
      "endDate": "2025-05-11",
      "href": "https://www.ethdam.com",
      "location": "Amsterdam",
      "country": "Netherlands",
      "continent": "Europe",
      "description": "Conference and hackathon gathering the best Privacy and Security builders",
      "imageUrl": "https://drive.google.com/file/d/12IW8m1LdF4AU95LskDle9ei_J09M3jz-/preview",
      "tags": ["Privacy", "Security", "Hackathon"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "ETHMilan",
      "startDate": "2025-06-24",
      "endDate": "2025-06-24",
      "href": "https://ethmilan.xyz",
      "location": "Milan",
      "country": "Italy",
      "continent": "Europe",
      "description": "Italy's Largest ETH & Web3 Conference",
      "imageUrl": "",
      "tags": ["Ethereum", "Web3", "Conference"],
      "categories": ["Conference"]
    },
    {
      "title": "Crecimiento",
      "startDate": "2025-03-05",
      "endDate": "2025-03-28",
      "href": "https://aleph.crecimiento.build/",
      "location": "Buenos Aires",
      "country": "Argentina",
      "continent": "South America",
      "description": "A pop-up city experiment bringing together visionaries and experts to transform Argentina into a startup & innovation hub",
      "imageUrl": "https://cdn.prod.website-files.com/6661b1a3c1bce60cd61fc966/669e83df3c3a7535a9cc05fa_1200xlogo.png",
      "tags": ["Innovation", "Startup", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "EthereumSF",
      "startDate": "2025-03-10",
      "endDate": "2025-03-16",
      "href": "https://ethereumsf.org/",
      "location": "San Francisco",
      "country": "United States",
      "continent": "North America",
      "description": "A decentralized, week-long event series across the Bay Area, focusing on d/acc, blockchain, and AI",
      "imageUrl": "",
      "tags": ["Blockchain", "AI", "Innovation"],
      "categories": ["Conference"]
    },
    {
      "title": "Building Blocks",
      "startDate": "2025-03-25",
      "endDate": "2025-03-29",
      "href": "https://buildingblockstlv.com/",
      "location": "Tel Aviv",
      "country": "Israel",
      "continent": "Asia",
      "description": "Building Blocks - Scaling Crypto Startups",
      "imageUrl": "",
      "tags": ["Startup", "Crypto", "Scaling"],
      "categories": ["Conference"]
    },
    {
      "title": "Paris P2P Festival",
      "startDate": "2025-04-04",
      "endDate": "2025-04-11",
      "href": "https://www.p2p.paris",
      "location": "Paris",
      "country": "France",
      "continent": "Europe",
      "description": "The Parisian community interested in P2P, Security & Cryptography technologies",
      "imageUrl": "https://p2p.paris/images/paris-p2p-thumbnail.jpg",
      "tags": ["P2P", "Security", "Cryptography"],
      "categories": ["Conference"]
    },
    {
      "title": "Appcon",
      "startDate": "2025-04-07",
      "endDate": "2025-04-13",
      "href": "https://appcon.org",
      "location": "Milan",
      "country": "Italy",
      "continent": "Europe",
      "description": "Discover Ethereum apps at Appcon - Interactive showcase bridging new adopters, developers, and investors",
      "imageUrl": "https://appcon.org/opengraph-image.png?1ef56b7e20f7b364",
      "tags": ["Ethereum", "Development", "Showcase"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHRome Hackathon",
      "startDate": "2025-04-11",
      "endDate": "2025-04-13",
      "href": "https://ethrome.org",
      "location": "Rome",
      "country": "Italy",
      "continent": "Europe",
      "description": "The hackathon for builders by builders",
      "imageUrl": "https://www.ethrome.org/opengraph-image.png",
      "tags": ["Hackathon", "Development", "Community"],
      "categories": ["Hackathon"]
    },
    {
      "title": "ETHBratislava",
      "startDate": "2025-05-23",
      "endDate": "2025-05-24",
      "href": "https://ethbratislava.com/",
      "location": "Bratislava",
      "country": "Slovakia",
      "continent": "Europe",
      "description": "Two-day conference and hackathon focused on sharing knowledge and sparking innovative ideas",
      "imageUrl": "https://framerusercontent.com/assets/IBAFZwu44FpNo95n3OoOapeFUyw.png",
      "tags": ["Conference", "Hackathon", "Innovation"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "EthAccra",
      "startDate": "2025-09-03",
      "endDate": "2025-09-06",
      "href": "https://ethaccra.xyz",
      "location": "Accra",
      "country": "Ghana",
      "continent": "Africa",
      "description": "Ghana's premier Ethereum event",
      "imageUrl": "http://eth-accra-website.vercel.app/assets/pngs/meta_image.png",
      "tags": ["Conference", "Community", "Development"],
      "categories": ["Conference"]
    },
    {
      "title": "ETHTokyo",
      "startDate": "2025-09-12",
      "endDate": "2025-09-15",
      "href": "https://lu.ma/eth-tokyo",
      "location": "Tokyo",
      "country": "Japan",
      "continent": "Asia",
      "description": "Tokyo's premier Ethereum event",
      "imageUrl": "https://images.lumacdn.com/calendar-cover-images/rv/316a4b25-a9fb-4ff0-ab1a-d7f23a2ba0e0",
      "tags": ["Conference", "Hackathon", "Community"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "Edge City Austin",
      "startDate": "2025-03-02",
      "endDate": "2025-03-07",
      "href": "https://www.edgecity.live/austin",
      "location": "Austin",
      "country": "United States",
      "continent": "North America",
      "description": "Edge City Austin - Innovation and technology gathering",
      "imageUrl": "https://cdn.prod.website-files.com/65b2cb5abdecf7cd7747e170/67aba5d16f625f40658dde92_edge-sxsw-10.png",
      "tags": ["Innovation", "Technology", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "Edge Expedition South Africa",
      "startDate": "2025-04-03",
      "endDate": "2025-04-12",
      "href": "https://www.edgecity.live/southafrica",
      "location": "Cape Town",
      "country": "South Africa",
      "continent": "Africa",
      "description": "Edge Expedition - Innovation and technology exploration in South Africa",
      "imageUrl": "https://cdn.prod.website-files.com/65b2cb5abdecf7cd7747e170/67802a19fb53c877dd9f5eb0_og-southafricaexpedition%20(1).png",
      "tags": ["Innovation", "Technology", "Community"],
      "categories": ["Conference"]
    },
    {
      "title": "ETH Cinco de Mayo",
      "startDate": "2025-05-01",
      "endDate": "2025-05-04",
      "href": "https://ethcdm.com/",
      "location": "Mexico City",
      "country": "Mexico",
      "continent": "North America",
      "description": "A combination of competition, workshops, networking, entrepreneurship and culture",
      "imageUrl": "https://ethcdm.com/assets/images/og-918.jpg",
      "tags": ["Hackathon", "Workshop", "Culture"],
      "categories": ["Conference", "Hackathon"]
    },
    {
      "title": "World Expo on Blockchain*",
      "startDate": "2025-05-10",
      "endDate": "2025-06-03",
      "href": "https://web2025.world/",
      "location": "Osaka",
      "country": "Japan",
      "continent": "Asia",
      "description": "Exploring financial inclusion, digital trust, data privacy and security in blockchain",
      "imageUrl": "https://framerusercontent.com/images/Ivp1oWg8CFUDERZIoey9dadW7E.png",
      "tags": ["Blockchain", "Privacy", "Security"],
      "categories": ["Conference"]
    }
  ]